# This file contains values from Cookiecutter

default_context:
  project_name: "statlearn"
  project_description: "Awesome `statlearn` is a Python cli/package created with https://github.com/Undertone0809/python-package-template"
  organization: "statlearn"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "xcz0"
  email: "hello@statlearn.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
